### ISSUE TITLE
App No Longer Shows Correct Transfer Function Screen

### ISSUE THREAD

**Issue by Cynopolis** [Herwig9820/controlSystemsApp-HP-Prime#1]
HP Prime Firmware Version: 2.1.14603

This is the view you get when you first start up the app after a fresh install of Control Systems. The transfer function view is no longer there and it's back to showing the default parametric view.

![image](https://user-images.githubusercontent.com/31545331/158077527-20554197-130e-4eed-8cb5-e4ad2dd29d1e.png)

I'm currently taking control systems and would love to have this app for the class. It seems you've done a great job with it and it has a lot of versatility.

**Comment by Herwig9820** [comment]
Hi, this is normal after a new installation. Please refer to the manual, chapter 15 - especially point 4, 5 and 6. 
Regards
